export const FETCH_MOVIE_AUTH = "FETCH_MOVIE_AUTH";

export const ADD_MOVIE_AUTH_REQUEST = "ADD_MOVIE_AUTH_REQUEST";
export const ADD_MOVIE_AUTH_SUCCESS = "ADD_MOVIE_AUTH_SUCCESS";
export const ADD_MOVIE_AUTH_FAILED = "ADD_MOVIE_AUTH_FAILED";

export const EDIT_MOVIE_AUTH_SUCCESS = "EDIT_MOVIE_AUTH_SUCCESS";
export const EDIT_MOVIE_AUTH_FAILED = "EDIT_MOVIE_AUTH_FAILED";