export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_COMMING = "FETCH_MOVIE_COMMING";
export const FETCH_MOVIE_DETAIL = "FETCH_MOVIE_DETAIL";

export const FETCH_MOVIE_DETAIL_SHOWTIME = "FETCH_MOVIE_DETAIL_SHOWTIME ";
