export const FETCH_USER_MANAGER = "FETCH_USER_MANAGER";

export const ADD_USER_AUTH_REQUEST = "ADD_USER_AUTH_REQUEST";
export const ADD_USER_AUTH_SUCCESS = "ADD_USER_AUTH_SUCCESS";
export const ADD_USER_AUTH_FAILED = "ADD_USER_AUTH_FAILED";

export const EDIT_USER_AUTH_SUCCESS = "EDIT_USER_AUTH_SUCCESS";
export const EDIT_USER_AUTH_FAILED = "EDIT_USER_AUTH_FAILED";

export const FECTH_DETAIL_USER_SUCCESS = "FECTH_DETAIL_USER_SUCCESS";
export const FECTH_DETAIL_USER_FAILED = "FECTH_DETAIL_USER_FAILED";
